image: gradle:jdk22-alpine

stages:
  - build
  - tests

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - gradle --build-cache build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

tests:
  stage: tests
  script:
    - gradle test
  artifacts:
    paths:
      - build/test-results/test
    when: always
    expire_in: 1 week
